"""
scenario_generator.py
---------------------

Author: Nicolas Bechstedt\\
Supervision: Nicolas Alaux\\
Other contributors: See README.md\\
License: See LICENSE.md

Description:
    This file generates the scenario files based on the input CSVs.
"""

import ast
import copy
from dataclasses import dataclass
import pickle
import logging
import os
from shutil import rmtree
from typing import Any, Literal

import polars as pl
from math import isnan

from pulse.config import (
    TASKS_PATH,
    ARCHETYPE_STOCK_DATA_PATH,
    SCENARIO_PATH,
)

from pulse.support.arguments import SchedulerArguments, schedulerArgs
from pulse.support.defines import (
    COUNTRY_CODE_LIST,
    TYPOLOGIES,
    COUNTRY_CODE_TO_COUNTRY,
    LIGHT,
    MEDIUM,
    DEEP,
)
from pulse.support.file_interaction import (
    load_energy_performance_data,
    load_std_refurbishment_rates,
    read_dataframe_from_excel,
)
from pulse.support.ui import format_list

from .task_list import TaskList

# ----------------------------------------------------------------------------------------------------
# Defines

L_APPLICATION: Literal[1] = 1
M_APPLICATION: Literal[2] = 2
H_APPLICATION: Literal[3] = 3

BASELINE: Literal["Baseline"] = "Baseline"
Y_2030: Literal["2030"] = "2030"
Y_2040: Literal["2040"] = "2040"
Y_2050: Literal["2050"] = "2050"

FULL_TIMBER = "1"
HYBRID_TIMBER = "2"

EP_NZEB = "2"

NUM_STRATEGIES = 10

COMMITMENT_LEVELS = {"1": 0.00, "2": 0.50, "3": 1.00, "4": 1.50}

START_YEAR = 2020
END_YEAR = 2050

NOT_IMPLEMENTED_MEASURES = ("1.2", "2.3", "7.1", "8.3", "10.2", "10.3")

# ----------------------------------------------------------------------------------------------------
# Helper functions that don't directly affect the functionality of reading the data


__COLLECTED_WARNINGS: dict[str, int] = {}


def collect_warning(message: str, no_count: bool = False) -> None:
    """This function colelcts the warnings into a file"""
    if no_count:
        if message not in __COLLECTED_WARNINGS:
            __COLLECTED_WARNINGS[message] = 1
    else:
        if message not in __COLLECTED_WARNINGS:
            __COLLECTED_WARNINGS[message] = 0

        __COLLECTED_WARNINGS[message] += 1


def clear_files(folder: str) -> None:
    """Clears the files generated by this script."""
    found_counter = 0

    tasks_path = TASKS_PATH.format(folder)

    if os.path.isfile(tasks_path):
        # print(f'Removing "{TASKS_FILE}".')
        os.remove(tasks_path)
        found_counter = found_counter + 1

    scenarios_folder = os.path.dirname(SCENARIO_PATH).format(folder)

    if os.path.isdir(scenarios_folder):
        found_counter += len(os.listdir(scenarios_folder))
        rmtree(scenarios_folder)

    if found_counter:
        print(f"Removed {found_counter} file{"s" if found_counter > 1 else ""}.")
    else:
        print("No files to clean.")


def print_collected_warnings() -> None:
    """This function prints all collected warnings"""

    for message, count in __COLLECTED_WARNINGS.items():
        if count > 1:
            print(f"{count}x ", end="")

        print(message)


def parse_boolean(string: str | None) -> bool | str | None:
    """Parses a string or None into a boolean."""
    if not isinstance(string, str):
        return string

    if string.lower() == "true":
        return True
    if string.lower() == "false":
        return False

    return string


def try_parse_array_string(string: str) -> list[str] | str:
    """This function tries to parse a string into an array. If that is not possible, the string gets returned"""
    try:
        result: list[str] = ast.literal_eval(string)
        assert isinstance(result, list)
        assert all(isinstance(item, str) for item in result)

        return result
    except (SyntaxError, ValueError):
        return string


# ----------------------------------------------------------------------------------------------------
# Types


@dataclass(init=True, frozen=True)
class Capacity:
    """A class to hold the capacity for a country to apply each measure."""

    country: str
    data: dict[str, dict[str, Literal[1, 2, 3]]]

    def __post_init__(self) -> None:

        for crs, data in self.data.items():
            v_2020 = data[BASELINE]
            v_2030 = data[Y_2030]
            v_2040 = data[Y_2040]
            v_2050 = data[Y_2050]

            assert (
                v_2020 <= v_2030 <= v_2040 <= v_2050
            ), f"Capacity should only ever increase but decreases for CRS {crs}! " + " <= ".join(
                str(v) for v in (v_2020, v_2030, v_2040, v_2050)
            )

    def __str__(self) -> str:
        string = f"{self.country}:"
        for crs, data in self.data.items():
            string += (
                f"\n\t{crs}: 2020: {data[BASELINE]} 2030: {data[Y_2030]} 2040: {data[Y_2040]} 2050: {data[Y_2050]}"
            )

        return string


@dataclass(init=True, frozen=True)
class Commitment:
    """A class to hold the levels of application of each measure."""

    name: str
    data: dict[str, float]

    def get_commitment(self, crs: str) -> float:
        """This function gets the commitment to a Carbon reduction strategy."""
        if crs in self.data:
            return self.data[crs]

        trimmed_crs = crs

        while len(trimmed_crs) > 0:

            trimmed_crs = trimmed_crs[0 : trimmed_crs.rfind(".")]

            if trimmed_crs in self.data:
                return self.data[trimmed_crs]

        raise KeyError(crs)

    def strategy_string(self, strategy: str) -> str:
        """This function gets the strategy string for a strategy."""
        matching_measures = {crs: value for crs, value in self.data.items() if crs.split(".", 1)[0] == strategy}

        if "9.12" in matching_measures and self.name != "APOLA" and matching_measures["9.12"] == 0.0:
            collect_warning("Removing 9.12 from strategy string as it should only be applied for APOLA!")
            matching_measures.pop("9.12")

        assert len(matching_measures), f"Strategy {strategy} does not have any matching measures!"

        minimum = min(matching_measures.values())
        maximum = max(matching_measures.values())

        min_level = None
        for i in range(1, len(COMMITMENT_LEVELS) + 1):
            if COMMITMENT_LEVELS[str(i)] > minimum:
                break

            min_level = i

        max_level = None
        for i in range(len(COMMITMENT_LEVELS), 0, -1):
            if COMMITMENT_LEVELS[str(i)] < maximum:
                break

            max_level = i
        if max_level is None:
            max_level = 4

        assert min_level is not None and min_level < 6, f"{minimum} is not a valid Commitment level!"
        assert max_level is not None and max_level > 0, f"{maximum} is not a valid Commitment level!"

        assert min_level <= max_level, f"Something went wrong! min ({min_level}) is higher than max ({max_level})!"

        if min_level == max_level:
            return str(min_level)

        return f"{min_level}{max_level}"

    def __str__(self) -> str:
        string = f"{self.name}:" + f" {self.data[""]}" if "" in self.data else ""
        for crs, value in self.data.items():
            if crs == "":
                continue

            string += "\n" + "    " * (crs.count(".") + 1) + f"{crs}: {value}"

        return string


class Measure:
    """A class to hold a single Measure of a Strategy."""

    def __init__(
        self,
        crs: str,
        low: dict[str, float],
        medium: dict[str, float],
        high: dict[str, float],
        other_data: dict[str, str],
    ) -> None:
        self.crs = crs
        self.low_data = low
        self.medium_data = medium
        self.high_data = high

        # Other miscellanious data
        self.other_data: dict[str, Any] = {
            "implementation": other_data["implementation"],
            "stock_activity_type_code": try_parse_array_string(other_data["stock_activity_type_code"]),
            "building_use_subtype_code": try_parse_array_string(other_data["building_use_subtype_code"]),
            "element_class_generic_name": try_parse_array_string(other_data["element_class_generic_name"]),
            "material_name_JRC_CDW": try_parse_array_string(other_data["material_name_JRC_CDW"]),
            "LCS_EN15978": try_parse_array_string(other_data["LCS_EN15978"]),
            "amount_material_kg_per_building": parse_boolean(other_data["amount_material_kg_per_building"]),
            "activity_in_out": try_parse_array_string(other_data["activity_in_out"]),
            "techflow_name_mmg": try_parse_array_string(other_data["techflow_name_mmg"]),
            "ind": try_parse_array_string(other_data["ind"]),
            "CRS_impact": other_data["CRS_impact"],
        }

    @property
    def strategy_crs(self) -> str:
        """The top-level Carbon Reduction Strategy code."""
        return self.crs[: self.crs.index(".")]

    @property
    def crs_impact(self) -> float:
        """The top-level Carbon Reduction Strategy code."""
        crs_impact = self.other_data["CRS_impact"]
        assert isinstance(crs_impact, (float, int))
        return float(crs_impact)

    def get_value(
        self, capacity: Literal[1, 2, 3], year: Literal["2030", "2040", "2050"], commitment_modifier: float
    ) -> float:
        """This function gets the value for a year and intensity value."""
        match capacity:
            case 1:
                current = self.low_data[year]
            case 2:
                current = self.medium_data[year]
            case 3:
                current = self.high_data[year]

        maximum = max(current, self.high_data[year])
        return min(current * commitment_modifier, maximum)

    def is_submeasure(self, crs: str) -> bool:
        """This function checks if the measure is a submeasure of the given measure string."""
        crs_split = crs.split(".")
        og_crs_split = self.crs.split(".")

        if len(crs_split) > len(og_crs_split):
            return False

        for val1, val2 in zip(crs_split, og_crs_split):
            if val1 != val2:
                return False

        return True

    def is_preprocessing(self) -> bool:
        """This function checks if the measure is a preprocessing measure."""
        implementation = self.other_data["implementation"]
        assert isinstance(implementation, str)

        return implementation == "preprocessing"

    def is_not_implemented(self) -> bool:
        """This function checks if the strategy is not implemented."""
        should_be_not_implemented = self.crs in NOT_IMPLEMENTED_MEASURES

        has_any_data = any(
            value is not None
            for dataset in (
                self.low_data,
                self.medium_data,
                self.high_data,
                self.other_data,
            )
            for value in dataset.values()
        )

        if has_any_data and should_be_not_implemented:
            collect_warning(f"Measure {self.crs} is marked as not implemented but has data!")

        if not has_any_data and not should_be_not_implemented:
            collect_warning(f"Measure {self.crs} is marked as implemented but has no data!")

        return should_be_not_implemented


@dataclass(init=True, frozen=True)
class Strategy:
    """A class to hold data on the Generic Strategies."""

    crs: str
    measures: list[Measure]


class Scenario:
    """This holds the Scenario Data."""

    country: str
    start: int
    end: int
    step_size: int
    commitment: Commitment | None
    data: dict[str, dict[str, Any]]

    def __init__(self, country: str, start: int, end: int, step_size: int) -> None:
        self.country = country

        self.start = start
        self.end = end
        self.step_size = step_size

        self.commitment = None

        self.data = {}

        self.__name: str | None = None

    def apply_strategies(self, capacity: Capacity, commitment: Commitment, strategies: list[Strategy]) -> None:
        """Apply strategies?"""
        self.commitment = commitment

        for strategy in strategies:
            for measure in strategy.measures:
                self.apply_measure(measure, capacity)

    def apply_floor_area(
        self, inter_values: tuple[float, float, float], variable: str, invert_data: bool = False
    ) -> None:
        """This function applies the values passed to the scenario data."""
        assert variable not in self.data, f'"{variable}"" seems to already be in data! Panicking!'

        data: dict[str, Any] = interpolate_decades(*inter_values)
        assert_valid_data(data, minimum=0, maximum=100)

        if invert_data:
            data = {key: 100 - value for key, value in data.items()}

        data["implementation"] = "stock"
        self.data[variable] = data

    def apply_use_of_empty(self, inter_values: tuple[float, float, float], use: str) -> None:
        """This function applies the values passed to the scenario data."""
        variable = "Use of empty"

        current_data = self.data.setdefault(variable, {"implementation": "stock"})

        data = interpolate_decades(*inter_values)
        assert_valid_data(data, minimum=0, maximum=100)

        index = {"empty dwellings": 0, "secondary dwellings": 1, "empty units": 2}[use]

        for year, value in data.items():
            year_data: tuple[int, int, int] = current_data.setdefault(year, (0, 0, 0))

            assert year_data[index] == 0, f'"{variable}" for {use} seems to already be in data! Panicking!'

            current_data[year] = year_data[:index] + (value,) + year_data[index + 1 :]

    def apply_refurbishment_rate(self, inter_values: tuple[float, float, float], residential: bool, level: str) -> None:
        """This function applies the values passed to the scenario data."""
        variable = f"Share of {"" if residential else "Non-"}Residential Refurbishments"

        current_data = self.data.setdefault(variable, {"implementation": "stock"})

        base_value = load_std_refurbishment_rates(self.country, residential=residential)[level] * 100

        data = interpolate_decades(*inter_values, baseline=base_value)
        assert_valid_data(data, minimum=0, maximum=100)

        for year, value in data.items():
            year_data: dict[str, float] = current_data.setdefault(year, {})

            assert year not in year_data, f'"{variable}"" seems to already be in data! Panicking!'

            year_data[level] = value

    def apply_share_of_new_conhea(
        self, inter_values: tuple[float, float, float], level: str, t_type: str, measure: Measure
    ) -> None:
        """This function applies a material shift to the scenario."""
        typologies = measure.other_data["building_use_subtype_code"]
        if isinstance(typologies, str):
            assert typologies == "*", f'stock_activity_type_code is invalid for measure {measure.crs}: "{typologies}"'
            typologies = TYPOLOGIES

        assert isinstance(typologies, list)

        data = interpolate_decades(*inter_values)
        assert_valid_data(data, minimum=0, maximum=100)

        for typology in typologies:
            variable = f"Share of new {typology} {t_type} {level}"
            assert variable not in self.data, f'"{variable}"" seems to already be in data! Panicking!'

            self.data[variable] = {"implementation": "stock"} | data

    def apply_share_of_energy_performance(
        self, inter_values: tuple[float, float, float], level: str, measure: Measure
    ) -> None:
        """This function applies a material shift to the scenario."""
        typologies = measure.other_data["building_use_subtype_code"]
        if isinstance(typologies, str):
            assert typologies == "*", f'stock_activity_type_code is invalid for measure {measure.crs}: "{typologies}"'
            typologies = TYPOLOGIES

        assert isinstance(typologies, list)

        baseline = load_energy_performance_data(self.country)[level] * 100

        data = interpolate_decades(*inter_values, baseline=baseline)
        assert_valid_data(data, minimum=0, maximum=100)

        for typology in typologies:
            variable = f"Share of new {typology} energy performance {level}"
            assert variable not in self.data, f'"{variable}"" seems to already be in data! Panicking!'

            self.data[variable] = {"implementation": "stock"} | data

    def apply_preprocessing(self, measure: Measure, inter_values: tuple[float, float, float]) -> None:
        """This function applies the values passed to the scenario data."""
        assert measure.crs not in self.data, f"Measure {measure.crs} seems to already be in data! Panicking!"

        if isnan(measure.crs_impact):
            collect_warning(f"Skipping measure {measure.crs} due to invalid CRS impact: {measure.crs_impact}")
            return

        multiplier = float(measure.crs_impact) / 10_000  # 100 * 100

        data = interpolate_decades(*inter_values)
        # assert_valid_data(data, minimum=0, maximum=100)

        self.data[measure.crs] = measure.other_data | {key: value * multiplier for key, value in data.items()}

    def apply_measure(self, measure: Measure, capacity: Capacity) -> None:
        """This function applies a measure to the Scenario"""
        assert self.commitment is not None, "Commitment is not set!"

        commitment_modifier = self.commitment.get_commitment(measure.crs)

        if commitment_modifier == 0:
            return

        if measure.crs == "9.12" and self.commitment.name != "APOLA":
            collect_warning(f"Measure {measure.crs} should only be applied for APOLA!")

        capacities = capacity.data

        inter_values = (
            measure.get_value(capacities[measure.strategy_crs][Y_2030], Y_2030, commitment_modifier),
            measure.get_value(capacities[measure.strategy_crs][Y_2040], Y_2040, commitment_modifier),
            measure.get_value(capacities[measure.strategy_crs][Y_2050], Y_2050, commitment_modifier),
        )

        match measure.crs:
            #
            # Floor area per person
            case "1.1":
                self.apply_floor_area(inter_values, "Floor area per person (NFA)", invert_data=True)
            #
            # Use of empty and secondary
            case "2.1":
                self.apply_floor_area(inter_values, "Share of buildings repurposed")
            case "2.2":
                self.apply_use_of_empty(inter_values, "empty dwellings")
                self.apply_use_of_empty(inter_values, "empty units")
            #
            # Timber construction
            case _ if measure.is_submeasure("4.1"):
                self.apply_share_of_new_conhea(inter_values, FULL_TIMBER, "construction", measure)
            case _ if measure.is_submeasure("4.2"):
                self.apply_share_of_new_conhea(inter_values, HYBRID_TIMBER, "construction", measure)
            #
            # Refurbishment rates
            case "9.1":
                self.apply_refurbishment_rate(inter_values, residential=True, level=LIGHT)
            case "9.2":
                self.apply_refurbishment_rate(inter_values, residential=True, level=MEDIUM)
            case "9.3":
                self.apply_refurbishment_rate(inter_values, residential=True, level=DEEP)
            case "9.4":
                self.apply_refurbishment_rate(inter_values, residential=False, level=LIGHT)
            case "9.5":
                self.apply_refurbishment_rate(inter_values, residential=False, level=MEDIUM)
            case "9.6":
                self.apply_refurbishment_rate(inter_values, residential=False, level=DEEP)
            #
            # Energy performance
            case _ if measure.crs in ("9.7", "9.8"):
                self.apply_share_of_energy_performance(inter_values, EP_NZEB, measure)
            #
            # Preprocessing
            case _ if measure.is_preprocessing():
                self.apply_preprocessing(measure, inter_values)
            case _:
                raise KeyError(f"Invalid measure found: {measure.crs}")

    @property
    def name(self) -> str:
        """The full formal name of the scenario"""
        if self.__name is None:
            assert self.commitment is not None

            strategy_strings: list[str] = []

            for i in range(1, NUM_STRATEGIES + 1):
                strategy_strings.append(self.commitment.strategy_string(str(i)))

            strategy_strings.append(self.commitment.strategy_string("4"))

            self.__name = f"{self.country}-{self.commitment.name}-{"-".join(strategy_strings)}"

        return self.__name

    def store(self, path: str) -> None:
        """This function stores the scenario to a specified File."""
        data = {
            "Name": self.name,
            "Model": "TUG",
            "Country": COUNTRY_CODE_TO_COUNTRY[self.country],
            "Start": self.start,
            "End": self.end,
            "Step size": self.step_size,
        } | self.data

        path = path.format(self.name)

        data_bytes = pickle.dumps(data)

        with open(path, "wb") as file:
            file.write(data_bytes)


# ----------------------------------------------------------------------------------------------------
# Program flow


def assert_valid_data(data: dict[str, int | float], minimum: int | float, maximum: int | float) -> None:
    """This function asserts that the data has the correct format."""
    all_years: list[str] = [str(year) for year in range(START_YEAR, END_YEAR + 1)]

    for year, value in data.items():
        if value > maximum:
            data[year] = maximum

    assert list(data.keys()) == all_years
    assert all(minimum <= value <= maximum for value in data.values())


def interpolate_decades(
    year_2030: float, year_2040: float, year_2050: float, baseline: float = 0.0
) -> dict[str, float]:
    """This function interpolates the years linearly."""
    result: dict[str, float] = {}

    for i in range(0, 11):
        result[str(2020 + i)] = baseline + (year_2030 - baseline) * i / 10

    for i in range(1, 11):
        result[str(2030 + i)] = year_2030 + (year_2040 - year_2030) * i / 10

    for i in range(1, 11):
        result[str(2040 + i)] = year_2040 + (year_2050 - year_2040) * i / 10

    return result


def get_extent_of_application(data: dict[str, str]) -> dict[str, Literal[1, 2, 3]]:
    """Gets the extent a country is capable of applying a Strategy."""

    def application_to_int(application: str) -> Literal[1, 2, 3]:
        """Application level to int."""

        match application:
            case _ if application in ("Low", "L"):
                return L_APPLICATION
            case _ if application in ("Medium", "M"):
                return M_APPLICATION
            case _ if application in ("High", "H"):
                return H_APPLICATION
            case _:
                raise KeyError(application)

    return {
        BASELINE: application_to_int(data[BASELINE]),
        Y_2030: application_to_int(data[Y_2030]),
        Y_2040: application_to_int(data[Y_2040]),
        Y_2050: application_to_int(data[Y_2050]),
    }


def get_base_capacities(capacities_path: str) -> list[Capacity]:
    """This function generated the Scenario versions"""
    capacities_df = read_dataframe_from_excel(capacities_path, "Capacities")

    capacities_df = capacities_df.rename({col: col.strip() for col in capacities_df.columns})
    capacities_df = capacities_df.with_columns(pl.col(pl.String).str.strip_chars())

    capacities: list[Capacity] = []

    for country in COUNTRY_CODE_LIST:
        relevant = capacities_df.filter(pl.col("country").str.contains(country, literal=True))

        if len(relevant) != NUM_STRATEGIES:
            found = len(relevant)
            print(f"Found {found} Strateg{"y" if found == 1 else "ies"} out of {NUM_STRATEGIES} for {country}!")
            continue

        capacity_data = {
            str(row["strategy_id"]): get_extent_of_application(row) for row in relevant.iter_rows(named=True)
        }

        capacities.append(Capacity(country, capacity_data))

    return capacities


def get_commitments(commitments_path: str) -> list[Commitment]:
    """This function generated the Scenario versions"""
    extension = os.path.splitext(commitments_path)[1]

    logging.getLogger("fastexcel.types.dtype").setLevel(logging.ERROR)

    if extension == ".xlsx":
        commitments_df = read_dataframe_from_excel(commitments_path, "Commitments")
    elif extension == ".parquet":
        commitments_df = pl.read_parquet(commitments_path)
    else:
        raise NotImplementedError(f'File extension "{extension}" is not supported!')

    schema: dict[str, pl.DataType] = {}

    for col, dtype in commitments_df.schema.items():
        if col in ("Scenario Name"):
            schema[col] = dtype
        else:
            schema[col] = pl.UInt16()

    commitments_df = pl.DataFrame(commitments_df, schema=schema)
    commitments_df = commitments_df.rename({col: " ".join(col.split()) for col in commitments_df.columns})
    commitments_df = commitments_df.with_columns(pl.col(pl.String).str.strip_chars())

    measures = [col for col in commitments_df.columns if col.startswith("CRS")]

    # Filling based on CRS hierarchy
    dependencies: dict[str, str] = {}

    for measure in measures:
        idx = measure.rfind(".")
        parent = measure[:idx] if idx != -1 else "Default"
        dependencies[measure] = parent

    dependencies = dict(sorted(dependencies.items(), key=lambda x: x[0].count(".")))
    relevant_cols = sorted(list(set(dependencies.keys()) - set(dependencies.values())))

    for comm, parent in dependencies.items():
        commitments_df = commitments_df.with_columns(
            pl.when(pl.col(comm).is_null()).then(pl.col(parent)).otherwise(pl.col(comm)).alias(comm)
        )

    commitments_df = commitments_df.select(["Scenario Name"] + relevant_cols)
    commitments_df = commitments_df.with_columns(pl.col(relevant_cols) / 100)
    commitments_df = commitments_df.rename({m: m[4:] for m in relevant_cols})

    base_commitments: list[Commitment] = []

    for data in commitments_df.iter_rows(named=True):
        base_commitments.append(Commitment(data.pop("Scenario Name"), data))

    return base_commitments


def get_strategies(path: str) -> list[Strategy]:
    """This function generated the Scenario versions"""
    strategies_df = read_dataframe_from_excel(path, sheet=None)

    strategies_df = strategies_df.rename({col: col.strip() for col in strategies_df.columns})
    strategies_df = strategies_df.with_columns(pl.col(pl.String).str.strip_chars())

    required_columns = {
        "CRS_code",
        "CRS_diffusion_2030_low",
        "CRS_diffusion_2030_medium",
        "CRS_diffusion_2030_high",
        "CRS_diffusion_2040_low",
        "CRS_diffusion_2040_medium",
        "CRS_diffusion_2040_high",
        "CRS_diffusion_2050_low",
        "CRS_diffusion_2050_medium",
        "CRS_diffusion_2050_high",
        "implementation",
        "stock_activity_type_code",
        "building_use_subtype_code",
        "element_class_generic_name",
        "material_name_JRC_CDW",
        "LCS_EN15978",
        "amount_material_kg_per_building",
        "activity_in_out",
        "techflow_name_mmg",
        "ind",
    }

    missing_cols = required_columns - set(strategies_df.columns)

    if missing_cols:
        raise ValueError(f"Strategies file is missing columns: {missing_cols}")

    strategies: list[Strategy] = []

    for crs in range(1, NUM_STRATEGIES + 1):
        regex = r"^" + str(crs) + r"\."

        relevant = strategies_df.filter(pl.col("CRS_code").str.contains(regex))

        if len(relevant) == 0:
            collect_warning(f"Found no Measures for Strategy {crs}!")
            continue

        measures: list[Measure] = [
            Measure(
                crs=row["CRS_code"],
                low={
                    Y_2030: row["CRS_diffusion_2030_low"],
                    Y_2040: row["CRS_diffusion_2040_low"],
                    Y_2050: row["CRS_diffusion_2050_low"],
                },
                medium={
                    Y_2030: row["CRS_diffusion_2030_medium"],
                    Y_2040: row["CRS_diffusion_2040_medium"],
                    Y_2050: row["CRS_diffusion_2050_medium"],
                },
                high={
                    Y_2030: row["CRS_diffusion_2030_high"],
                    Y_2040: row["CRS_diffusion_2040_high"],
                    Y_2050: row["CRS_diffusion_2050_high"],
                },
                other_data=row,
            )
            for row in relevant.iter_rows(named=True)
        ]

        measures = [measure for measure in measures if not measure.is_not_implemented()]

        strategies.append(Strategy(str(crs), measures))

    return strategies


def do_not_generate_data_for_country(country: str, countries: list[str]) -> bool:
    """Checks if the archetype stock data exists for the country."""
    generate_data = os.path.exists(ARCHETYPE_STOCK_DATA_PATH.format(country.lower()))

    generate_data &= country.upper() in countries

    return not generate_data


def create_and_store_scenarios(
    base_capacities: list[Capacity],
    commitments: list[Commitment],
    strategies: list[Strategy],
    args: SchedulerArguments,
) -> list[str]:
    """
    This function generates the Scenarios based on the given data.
    Returns the list of commitments that were generated.
    """

    tasks = TaskList(args)
    print("[" + " " * (len(args.countries) + 1) + "]", end="\033[2G", flush=True)

    scenario_path = SCENARIO_PATH.format(args.output_folder, r"{}")

    for base_capacity in base_capacities:
        if do_not_generate_data_for_country(base_capacity.country, args.countries):
            continue

        scenario = Scenario(base_capacity.country, args.start_year, args.end_year, args.step_size)

        for commitment in commitments:
            new_scenario = copy.deepcopy(scenario)
            new_scenario.apply_strategies(base_capacity, commitment, strategies)

            tasks.add_scenario(new_scenario.name)
            new_scenario.store(scenario_path)

        print("#", end="", flush=True)

    tasks.store()
    print("#", flush=True)

    return list(set(commitment.name for commitment in commitments))


def generate_scenarios() -> None:
    """The main method that runs the generation."""
    args = schedulerArgs
    clear_files(args.output_folder)

    print(f"Measures {format_list(NOT_IMPLEMENTED_MEASURES)} are not implemented.")
    print("Calculating scenarios...")

    scenario_path = os.path.dirname(SCENARIO_PATH).format(args.output_folder)

    os.makedirs(scenario_path, exist_ok=True)

    comms = create_and_store_scenarios(
        get_base_capacities(args.capacities_file),
        get_commitments(args.commitments_file),
        get_strategies(args.strategies_file),
        args,
    )

    print_collected_warnings()

    print(f"Generated commitments: {format_list(comms, sort=True)}")
